In [1]:
# data analysis and wrangling
import pandas as pd
import numpy as np
import random as rnd

# visualization

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# machine learning
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier

train_df = pd.read_csv('train.csv')
print(train_df.shape)
test_df = pd.read_csv('test.csv')
combine = [train_df, test_df]

(61878, 95)


In [2]:
print(train_df.head())
print(train_df.tail())
train_df.notnull()


   id  feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  feat_9  \
0   1       1       0       0       0       0       0       0       0       0   
1   2       0       0       0       0       0       0       0       1       0   
2   3       0       0       0       0       0       0       0       1       0   
3   4       1       0       0       1       6       1       5       0       0   
4   5       0       0       0       0       0       0       0       0       0   

    ...     feat_85  feat_86  feat_87  feat_88  feat_89  feat_90  feat_91  \
0   ...           1        0        0        0        0        0        0   
1   ...           0        0        0        0        0        0        0   
2   ...           0        0        0        0        0        0        0   
3   ...           0        1        2        0        0        0        0   
4   ...           1        0        0        0        0        1        0   

   feat_92  feat_93   target  
0        0        0

id  feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  \
0      True    True    True    True    True    True    True    True    True   
1      True    True    True    True    True    True    True    True    True   
2      True    True    True    True    True    True    True    True    True   
3      True    True    True    True    True    True    True    True    True   
4      True    True    True    True    True    True    True    True    True   
5      True    True    True    True    True    True    True    True    True   
6      True    True    True    True    True    True    True    True    True   
7      True    True    True    True    True    True    True    True    True   
8      True    True    True    True    True    True    True    True    True   
9      True    True    True    True    True    True    True    True    True   
10     True    True    True    True    True    True    True    True    True   
11     True    True    True    True    True    True    True    True    True   
12     True    True    True    True    True    True    True    True    True   
13     True    True    True    True    True    True    True    True    True   
14     True    True    True    True    True    True    True    True    True   
15     True    True    True    True    True    True    True    True    True   
16     True    True    True    True    True    True    True    True    True   
17     True    True    True    True    True    True    True    True    True   
18     True    True    True    True    True    True    True    True    True   
19     True    True    True    True    True    True    True    True    True   
20     True    True    True    True    True    True    True    True    True   
21     True    True    True    True    True    True    True    True    True   
22     True    True    True    True    True    True    True    True    True   
23     True    True    True    True    True    True    True    True    True   
24     True    True    True    True    True    True    True    True    True   
25     True    True    True    True    True    True    True    True    True   
26     True    True    True    True    True    True    True    True    True   
27     True    True    True    True    True    True    True    True    True   
28     True    True    True    True    True    True    True    True    True   
29     True    True    True    True    True    True    True    True    True   
...     ...     ...     ...     ...     ...     ...     ...     ...     ...   
61848  True    True    True    True    True    True    True    True    True   
61849  True    True    True    True    True    True    True    True    True   
61850  True    True    True    True    True    True    True    True    True   
61851  True    True    True    True    True    True    True    True    True   
61852  True    True    True    True    True    True    True    True    True   
61853  True    True    True    True    True    True    True    True    True   
61854  True    True    True    True    True    True    True    True    True   
61855  True    True    True    True    True    True    True    True    True   
61856  True    True    True    True    True    True    True    True    True   
61857  True    True    True    True    True    True    True    True    True   
61858  True    True    True    True    True    True    True    True    True   
61859  True    True    True    True    True    True    True    True    True   
61860  True    True    True    True    True    True    True    True    True   
61861  True    True    True    True    True    True    True    True    True   
61862  True    True    True    True    True    True    True    True    True   
61863  True    True    True    True    True    True    True    True    True   
61864  True    True    True    True    True    True    True    True    True   
61865  True    True    True    True    True    True    True    True    True   
61866  True    True    True    True    True    True    True

In [3]:
# print(train_df.columns.values)
# train_df.head()
# train_df.tail()
print(train_df.info())
print('_'*40)
print(test_df.info())
print(train_df.describe())
print(train_df.describe(include=['O']))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61878 entries, 0 to 61877
Data columns (total 95 columns):
id         61878 non-null int64
feat_1     61878 non-null int64
feat_2     61878 non-null int64
feat_3     61878 non-null int64
feat_4     61878 non-null int64
feat_5     61878 non-null int64
feat_6     61878 non-null int64
feat_7     61878 non-null int64
feat_8     61878 non-null int64
feat_9     61878 non-null int64
feat_10    61878 non-null int64
feat_11    61878 non-null int64
feat_12    61878 non-null int64
feat_13    61878 non-null int64
feat_14    61878 non-null int64
feat_15    61878 non-null int64
feat_16    61878 non-null int64
feat_17    61878 non-null int64
feat_18    61878 non-null int64
feat_19    61878 non-null int64
feat_20    61878 non-null int64
feat_21    61878 non-null int64
feat_22    61878 non-null int64
feat_23    61878 non-null int64
feat_24    61878 non-null int64
feat_25    61878 non-null int64
feat_26    61878 non-null int64
feat_27    61878 non-null i

In [4]:
train_drop_id_target = train_df.drop(['id','target'],axis=1)
train_target = train_df['target']
train_drop_id_target.head()
train_target.head()

0    Class_1
1    Class_1
2    Class_1
3    Class_1
4    Class_1
Name: target, dtype: object

In [5]:
train_drop_id_target.to_csv("train_X.csv", header=True, index=False)
train_target.to_csv("train_y.csv", header=True, index=False)

In [6]:
pd.read_csv("train_X.csv")

feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  feat_9  \
0           1       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       1       0   
2           0       0       0       0       0       0       0       1       0   
3           1       0       0       1       6       1       5       0       0   
4           0       0       0       0       0       0       0       0       0   
5           2       1       0       0       7       0       0       0       0   
6           2       0       0       0       0       0       0       2       0   
7           0       0       0       0       0       0       0       0       0   
8           0       0       0       0       0       0       0       4       0   
9           0       0       0       0       0       0       1       0       0   
10          0       1       1       2       0       0       2       1       0   
11          0       1       2       1       0       0       0       0       0   
12          1       0       1       0       0       0       0       1       0   
13          0       0       0       1       0       0       0       2       0   
14          0       0       0       0       0       0       0       0       0   
15          0       0       0       2       0       0       0       1       0   
16          0       0       0       0       0       0       0       0       0   
17          0       0       0       0       0       0       0       0       0   
18          0       0       0       0       0       0       0       1       0   
19          0       0       0       0       0       0       0       0       0   
20          0       0       2       0       0       0       0       0       0   
21          0       0       0       0       0       0       0       0       0   
22          0       0       0       0       0       0       0       4       0   
23          0       0       0       0       1       0       0       1       1   
24          0       0       0       0       0       0       0       1       0   
25          0       0       0       0       0       0       0       3       0   
26          2       0       0       0       0       0       0       4       0   
27          0       0       0       0       0       0       0       1       0   
28          0       0       0       0       3       0       0       0       0   
29          2       0       0       0       0       0       4       1       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
61848       0       0       0       0       0       0       0       2       0   
61849       5       0       1       1       0       0       1       1       0   
61850       0       0       1       0       0       0       0       6       0   
61851       3       0       0       0       0       0       0       0       0   
61852       0       0       0       0       0       0       0       6       0   
61853       0       0       0       0       0       0       0       0       0   
61854       0       0       1       0       0       0       0       0       0   
61855       0       0       0       0       0       0       0       0       0   
61856       0       0       1       0       0       0       1       3       0   
61857       0       0       0       0       0       0       0      12       0   
61858       4       1       0       0       0       0       0      14       0   
61859       0       0       0       0       1       0       0       2       0   
61860       0       0       0       0       0       0       0       3       0   
61861       0       0       0       0       0       0       0      12       0   
61862       2       0       0       0       0       0       0       1       3   
61863       0       0       0       0       1       0       0       4       0   
61864       0       0       0       0       0       0       0       1       0   
61865       0       0       0       0 

In [37]:
X = train_drop_id_target.values
X
print((train_drop_id_target.shape))

array([[ 1,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ..., 
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 1,  0,  0, ...,  3, 10,  0],
       [ 0,  0,  0, ...,  0,  2,  0]], dtype=int64)

In [8]:
y = train_target.values
y
y.shape
print(train_target.shape)

(61878,)


In [36]:
y = y.reshape(-1)
y

array(['Class_1', 'Class_1', 'Class_1', ..., 'Class_9', 'Class_9',
       'Class_9'], dtype=object)

In [10]:
print("y shape:", y.shape)

y shape: (61878,)


In [11]:
X.shape

(61878, 93)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
print("X train:", X_train.shape)
print("y train:", y_train.shape)
print()
print("X test: ", X_test.shape)
print("y test: ", y_test.shape)

X train: (49502, 93)
y train: (49502,)

X test:  (12376, 93)
y test:  (12376,)


In [14]:
logreg = LogisticRegression()

In [15]:
logreg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
y_train_pred = logreg.predict(X_train)
y_train_pred
acc_log = round(logreg.score(X_train, y_train)*100 , 3)
acc_log

75.721999999999994

In [17]:
y_test_pred = logreg.predict(X_test)
y_test_pred

array(['Class_2', 'Class_7', 'Class_6', ..., 'Class_9', 'Class_2',
       'Class_7'], dtype=object)

In [18]:
from sklearn.metrics import accuracy_score
accuracy_train = accuracy_score(y_train, y_train_pred)
accuracy_test = accuracy_score(y_test, y_test_pred)
print(accuracy_train ,  accuracy_test )

0.757221930427 0.756868131868


In [19]:
# print(train_df.head())
coeff_df = pd.DataFrame(train_drop_id_target.columns)
#print(coeff_df.shape)
#print(pd.Series(logreg.coef_[0]))
coeff_df.columns = ['Feature']
coeff_df["Correlation"] = pd.Series(logreg.coef_[0])

coeff_df.sort_values(by='Correlation', ascending=False)

Feature  Correlation
80  feat_81     0.333539
36  feat_37     0.289088
76  feat_77     0.284721
16  feat_17     0.227791
5    feat_6     0.226735
60  feat_61     0.191951
65  feat_66     0.186694
69  feat_70     0.169017
22  feat_23     0.155778
29  feat_30     0.145851
43  feat_44     0.144245
4    feat_5     0.138937
54  feat_55     0.134401
6    feat_7     0.109439
78  feat_79     0.105671
75  feat_76     0.091283
19  feat_20     0.088239
52  feat_53     0.081675
83  feat_84     0.077432
17  feat_18     0.075999
23  feat_24     0.072426
66  feat_67     0.067776
91  feat_92     0.067122
48  feat_49     0.061675
27  feat_28     0.061621
70  feat_71     0.056059
51  feat_52     0.045788
11  feat_12     0.045508
50  feat_51     0.044400
61  feat_62     0.042576
..      ...          ...
85  feat_86    -0.140382
18  feat_19    -0.154796
56  feat_57    -0.155721
28  feat_29    -0.156493
1    feat_2    -0.161935
59  feat_60    -0.166187
12  feat_13    -0.169695
74  feat_75    -0.183377
71  feat_72    -0.183656
89  feat_90    -0.184574
73  feat_74    -0.196879
67  feat_68    -0.200073
34  feat_35    -0.210315
32  feat_33    -0.219343
81  feat_82    -0.220586
68  feat_69    -0.243496
41  feat_42    -0.246338
40  feat_41    -0.259203
33  feat_34    -0.301976
8    feat_9    -0.310832
49  feat_50    -0.340868
13  feat_14    -0.350101
92  feat_93    -0.351206
24  feat_25    -0.353415
39  feat_40    -0.389011
30  feat_31    -0.391979
14  feat_15    -0.420366
10  feat_11    -0.468797
57  feat_58    -0.501386
42  feat_43    -1.109647

[93 rows x 2 columns]

In [20]:
# Support Vector Machines

svc = SVC()
svc.fit(X_train, y_train)
Y_pred = svc.predict(X_test)
acc_svc = round(svc.score(X_train, y_train) * 100, 2)
acc_svc

86.579999999999998

In [38]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, y_train)
Y_pred = knn.predict(X_test)
acc_knn = round(knn.score(X_train, y_train) * 100, 2)
acc_knn

87.480000000000004

In [22]:
print(y_train[:1])

['Class_2']


In [23]:
# Gaussian Naive Bayes

gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
Y_pred = gaussian.predict(X_test)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)
acc_gaussian

61.520000000000003

In [39]:
# Perceptron

perceptron = Perceptron()
perceptron.fit(X_train, y_train)
Y_pred = perceptron.predict(X_test)
acc_perceptron = round(perceptron.score(X_train, y_train) * 100, 2)
acc_perceptron

C:\Users\Umesh.k\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:84: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


70.879999999999995

In [25]:
# Linear SVC

linear_svc = LinearSVC()
linear_svc.fit(X_train, y_train)
Y_pred = linear_svc.predict(X_test)
acc_linear_svc = round(linear_svc.score(X_train, y_train) * 100, 2)
acc_linear_svc

74.909999999999997

In [40]:
# Stochastic Gradient Descent

sgd = SGDClassifier()
sgd.fit(X_train, y_train)
Y_pred = sgd.predict(X_test)
acc_sgd = round(sgd.score(X_train, y_train) * 100, 2)
acc_sgd

C:\Users\Umesh.k\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:84: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


69.230000000000004

In [43]:
# Decision Tree

decision_tree = DecisionTreeClassifier(criterion='gini', splitter='best',max_depth=20,min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, class_weight=None, presort=False)
decision_tree.fit(X_train, y_train)
Y_pred = decision_tree.predict(X_test)
acc_decision_tree = round(decision_tree.score(X_train, y_train) * 100, 2)
acc_decision_tree

82.620000000000005

In [46]:
# Random Forest

random_forest = RandomForestClassifier(n_estimators=10)
random_forest.fit(X_train, y_train)
Y_pred = random_forest.predict(X_test)
print(Y_pred)
random_forest.score(X_train, y_train)
acc_random_forest = round(random_forest.score(X_train, y_train) * 100, 2)
acc_random_forest

[6 6 5 ..., 8 1 6]


99.269999999999996

In [49]:
models = pd.DataFrame({
    'Model': ['Support Vector Machines', 'KNN', 'Logistic Regression', 
              'Random Forest', 'Naive Bayes', 'Perceptron', 
              'Stochastic Gradient Decent', 'Linear SVC', 
              'Decision Tree'],
    'Score': [acc_svc, acc_knn, acc_log, 
              acc_random_forest, acc_gaussian, acc_perceptron, 
              acc_sgd, acc_linear_svc, acc_decision_tree]})
models.sort_values(by='Score', ascending=False)

Model   Score
3               Random Forest  99.270
1                         KNN  87.480
0     Support Vector Machines  86.580
8               Decision Tree  82.620
2         Logistic Regression  75.722
7                  Linear SVC  74.910
5                  Perceptron  70.880
6  Stochastic Gradient Decent  69.230
4                 Naive Bayes  61.520

In [48]:
from IPython.display import display, HTML
# print(y_train[:1])
train_df = pd.read_csv('train.csv')


# import labelencoder
from sklearn.preprocessing import LabelEncoder
# instantiate labelencoder object
le = LabelEncoder()


# apply le on categorical feature columns
train_df['target'] = le.fit_transform(train_df['target'])


print(train_df['target'].value_counts())
display(train_df.head())

independant_cols = train_df.columns.tolist()
print(len(independant_cols))
independant_cols.remove('id')
independant_cols.remove('target')


X_train, X_test, y_train, y_test = train_test_split(train_df[independant_cols], train_df['target'], 
                                                    test_size=0.2, random_state=42)




from sklearn.metrics import classification_report,confusion_matrix,roc_curve,auc
dtree = DecisionTreeClassifier(random_state=0, max_depth=5  )
dtree.fit(X_train,y_train)


Y_train_predict = dtree.predict(X_train)
print(Y_train_predict[:5])
print(confusion_matrix(y_train,Y_train_predict))
print(classification_report(y_train,Y_train_predict))

Y_test_predict = dtree.predict(X_test)
print(confusion_matrix(y_test,Y_test_predict))
print(classification_report(y_test,Y_test_predict))

1    16122
5    14135
7     8464
2     8004
8     4955
6     2839
4     2739
3     2691
0     1929
Name: target, dtype: int64


id  feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  feat_9  \
0   1       1       0       0       0       0       0       0       0       0   
1   2       0       0       0       0       0       0       0       1       0   
2   3       0       0       0       0       0       0       0       1       0   
3   4       1       0       0       1       6       1       5       0       0   
4   5       0       0       0       0       0       0       0       0       0   

    ...    feat_85  feat_86  feat_87  feat_88  feat_89  feat_90  feat_91  \
0   ...          1        0        0        0        0        0        0   
1   ...          0        0        0        0        0        0        0   
2   ...          0        0        0        0        0        0        0   
3   ...          0        1        2        0        0        0        0   
4   ...          1        0        0        0        0        1        0   

   feat_92  feat_93  target  
0        0        0       0  
1        0        0       0  
2        0        0       0  
3        0        0       0  
4        0        0       0  

[5 rows x 95 columns]

95
[1 1 1 1 1]
[[    4  1425     0     0     0    58     0    40     3]
 [    0 12767     0     0    30    17     0   128     2]
 [    0  6316    10     0     4     1     0   112     0]
 [    0  2087     0     0    18    32     0    16     0]
 [    0   193     0     0  1978     0     0     2     1]
 [    1  2413     2     0    13  8727     0    94     1]
 [    1  2008     0     0    28    86     2   162     0]
 [    0  4037     0     0    11    90     0  2651     1]
 [    2  3749     0     0     8    44     0    82    45]]
             precision    recall  f1-score   support

          0       0.50      0.00      0.01      1530
          1       0.36      0.99      0.53     12944
          2       0.83      0.00      0.00      6443
          3       0.00      0.00      0.00      2153
          4       0.95      0.91      0.93      2174
          5       0.96      0.78      0.86     11251
          6       1.00      0.00      0.00      2287
          7       0.81      0.39      0.53    

C:\Users\Umesh.k\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [31]:
from sklearn.metrics import classification_report,confusion_matrix,roc_curve,auc
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)

Y_train_predict = dtree.predict(X_train)
Y_train_predict
print(confusion_matrix(y_train,Y_train_predict))
print(classification_report(y_train,Y_train_predict))

[[ 1530     0     0     0     0     0     0     0     0]
 [    0 12944     0     0     0     0     0     0     0]
 [    0     0  6443     0     0     0     0     0     0]
 [    0     0     0  2153     0     0     0     0     0]
 [    0     0     0     0  2174     0     0     0     0]
 [    0     0     0     0     0 11251     0     0     0]
 [    0     0     0     0     0     0  2287     0     0]
 [    0     0     0     0     0     0     0  6790     0]
 [    0     0     0     0     0     0     0     0  3930]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00      1530
          1       1.00      1.00      1.00     12944
          2       1.00      1.00      1.00      6443
          3       1.00      1.00      1.00      2153
          4       1.00      1.00      1.00      2174
          5       1.00      1.00      1.00     11251
          6       1.00      1.00      1.00      2287
          7       1.00      1.00      1.00      6790
        